steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/blmayer/github.com/blmayer/gopip:${SHORT_SHA}'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/blmayer/github.com/blmayer/gopip
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - gopip
      - '--image'
      - 'gcr.io/blmayer/github.com/blmayer/gopip:${SHORT_SHA}'
      - '--region'
      - us-central1
      - '--platform'
      - managed
      - '--allow-unauthenticated'
